# Generated by Django 5.2.4 on 2025-09-07 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('senha_hash', models.CharField(max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('comum', 'Usuário Comum')], default='comum', max_length=10, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, null=True, unique=True)),
                ('setor_origem', models.CharField(max_length=100, null=True)),
                ('data_abertura', models.DateField(null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='aberto', max_length=15, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('tabela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='scpiapp.tabela')),
            ],
        ),
        migrations.AddField(
            model_name='tabela',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas', to='scpiapp.usuario'),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel')], max_length=10, null=True)),
                ('parametros_filtro', models.JSONField(null=True)),
                ('data_geracao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='scpiapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR', 'Criar'), ('ATUALIZAR', 'Atualizar'), ('EXCLUIR', 'Excluir')], max_length=15, null=True)),
                ('detalhes', models.TextField(null=True)),
                ('data_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='scpiapp.processo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acoes_auditadas', to='scpiapp.usuario')),
            ],
        ),
    ]
