# Generated by Django 5.2.5 on 2025-09-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scpiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabela',
            new_name='TabelaProcessos',
        ),
    ]
