# Generated by Django 5.2.5 on 2025-09-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scpiapp', '0002_rename_tabela_tabelaprocessos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='descricao',
            new_name='assunto',
        ),
        migrations.RenameField(
            model_name='processo',
            old_name='numero',
            new_name='numero_processo',
        ),
        migrations.RenameField(
            model_name='processo',
            old_name='setor_origem',
            new_name='setor',
        ),
        migrations.AddField(
            model_name='processo',
            name='bolsa',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_retorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='matricula',
            field=models.CharField(default='000000', max_length=50),
        ),
        migrations.AddField(
            model_name='processo',
            name='nome',
            field=models.CharField(default='Nome Padrão', max_length=255),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='em_andamento', max_length=20),
        ),
    ]
