# Generated by Django 5.2.5 on 2025-09-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scpiapp', '0003_rename_descricao_processo_assunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='setor',
            field=models.CharField(choices=[('CIC', 'CIC'), ('DPQ', 'DPQ')], max_length=100, null=True),
        ),
    ]
