# Generated by Django 5.2.5 on 2025-09-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scpiapp', '0004_processo_observacoes_alter_processo_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='bolsa',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_abertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processo',
            name='setor',
            field=models.CharField(blank=True, choices=[('CIC', 'CIC'), ('DPQ', 'DPQ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(blank=True, choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], max_length=20, null=True),
        ),
    ]
