# Generated by Django 5.2.4 on 2025-09-25 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scpiapp', '0005_alter_processo_bolsa_alter_processo_data_abertura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='tabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='scpiapp.tabelaprocessos'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='scpiapp.processo'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
