# Generated by Django 5.2.5 on 2025-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scpiapp', '0006_auditoria_tabela_alter_auditoria_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='setor',
            field=models.CharField(blank=True, choices=[('CIC', 'CIC'), ('DPQ', 'DPQ'), ('Financeiro', 'Financeiro'), ('RH', 'RH'), ('TI', 'TI'), ('Operações', 'Operações'), ('Marketing', 'Marketing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(blank=True, choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], max_length=20, null=True),
        ),
    ]
