# Generated by Django 5.2.5 on 2025-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scpiapp', '0007_alter_processo_setor_alter_processo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='setor',
            field=models.CharField(blank=True, choices=[('CIC', 'CIC'), ('DPQ', 'DPQ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(blank=True, choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], max_length=20, null=True),
        ),
    ]
