# Generated by Django 6.0.2 on 2026-04-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scpiapp', '0008_alter_processo_setor_alter_processo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
